import { useState } from "react";
import { GraduationCap, Plus, Trash2, Eye, EyeOff, ClipboardList, Users } from "lucide-react";
import { useStore, type Assignment, type Constraint } from "../lib/store";
import { Panel, Button, Badge, Select, Callout, Toggle } from "../components/ui";

const SCENARIOS: (Omit<Assignment, "id" | "createdAt"> & { code: string; titleFa: string; descFa: string; hiddenFa: string })[] = [
  { code: "A", title: "Design a 10 km access link", titleFa: "طراحی لینک دسترسی ۱۰ کیلومتری", description: "Design a 10 km, 1 Gb/s link at 1310 nm using a Fabry–Perot laser and PIN receiver. Received power must be ≥ −16 dBm with ≥ 3 dB margin.", descFa: "لینک ۱۰ km با نرخ ۱ Gb/s در ۱۳۱۰ nm با لیزر فابری–پرو و گیرنده PIN طراحی کنید. توان دریافتی باید ≥ −16 dBm با حاشیه ≥ 3 dB باشد.", timeLimit: 30, hidden: "FP @ 0 dBm, 2 connectors (0.8 dB), 2 splices (0.2 dB), 10 km × 0.35 = 3.5 dB → Prx ≈ −4.5 dBm. Margin vs −19 dBm PIN ≈ 14 dB.", hiddenFa: "FP در 0 dBm، ۲ کانکتور (0.8 dB)، ۲ اسپلایس (0.2 dB)، ۱۰ km × 0.35 = 3.5 dB ← Prx ≈ −4.5 dBm. حاشیه نسبت به PIN −19 dBm ≈ 14 dB.", constraints: [{ key: "length", op: ">=", value: 10, label: "Length" }, { key: "Prx", op: ">=", value: -16, label: "Received power" }, { key: "margin", op: ">=", value: 3, label: "Margin" }, { key: "errors", op: "<=", value: 0, label: "No physical errors" }], disabled: ["edfa", "raman"], fault: "none" },
  { code: "B", title: "Design an 80 km link at 1550 nm", titleFa: "طراحی لینک ۸۰ کیلومتری در ۱۵۵۰ nm", description: "Design an 80 km, 10 Gb/s link at 1550 nm with received power ≥ −18 dBm. Choose fiber, transmitter, receiver, amplifier, connectors and splices. Watch the dispersion limit.", descFa: "لینک ۸۰ km با ۱۰ Gb/s در ۱۵۵۰ nm طراحی کنید که توان دریافتی حداقل −18 dBm باشد. فیبر، فرستنده، گیرنده، تقویت‌کننده، کانکتور و اسپلایس را خودتان انتخاب کنید. مراقب حد پاشندگی باشید.", timeLimit: 45, hidden: "DFB +3 dBm, 80 km G.652 (16 dB), 2 conn + 16 splices (2.6 dB) → −15.6 dBm. Dispersion 17×80×0.1 = 136 ps > 25 ps allowed → add ~3 km DCF (−240 ps/nm) or use coherent Rx.", hiddenFa: "DFB با +3 dBm، ۸۰ km G.652 (16 dB)، ۲ کانکتور + ۱۶ اسپلایس (2.6 dB) ← −15.6 dBm. پاشندگی 17×80×0.1 = 136 ps > 25 ps مجاز ← ~۳ km DCF (−240 ps/nm) اضافه کنید یا از گیرنده همدوس استفاده کنید.", constraints: [{ key: "length", op: ">=", value: 80, label: "Length" }, { key: "lambda", op: "==", value: 1550, label: "Wavelength" }, { key: "Prx", op: ">=", value: -18, label: "Received power" }, { key: "errors", op: "<=", value: 0, label: "No physical errors" }], disabled: [], fault: "none" },
  { code: "C", title: "Troubleshoot a link with OTDR", titleFa: "عیب‌یابی لینک با OTDR", description: "Using Experiment 8 (OTDR), a 40 km link shows 6 dB more loss than commissioned. Locate the faulty event, identify its type (bend / bad splice / break) and report distance ±100 m.", descFa: "با آزمایش ۸ (OTDR)، لینک ۴۰ km حدود ۶ dB تلفات بیشتر از زمان راه‌اندازی دارد. رویداد معیوب را مکان‌یابی کنید، نوع آن (خمش / اسپلایس معیوب / شکستگی) را مشخص کنید و فاصله را با دقت ±100 m گزارش دهید.", timeLimit: 20, hidden: "Macro-bend at 22.0 km (non-reflective step, 0.9 dB @1550, larger at 1625 nm).", hiddenFa: "خمش در ۲۲٫۰ km (پله غیربازتابی، 0.9 dB در ۱۵۵۰، بزرگ‌تر در ۱۶۲۵ nm).", constraints: [{ key: "components", op: ">=", value: 3, label: "Report submitted" }], disabled: [], fault: "bend@22" },
  { code: "D", title: "Select the best laser & receiver", titleFa: "انتخاب مناسب‌ترین لیزر و گیرنده", description: "For a 60 km, 10 Gb/s link, choose the source (LED/FP/DFB) and receiver (PIN/APD/coherent) that achieves BER ≤ 1e-12 at minimum cost. Justify with dispersion and power budget.", descFa: "برای لینک ۶۰ km و ۱۰ Gb/s منبع (LED/FP/DFB) و گیرنده (PIN/APD/همدوس) را طوری انتخاب کنید که BER ≤ 1e-12 با کمترین هزینه حاصل شود. با بودجه پاشندگی و توان توجیه کنید.", timeLimit: 30, hidden: "DFB (Δλ 0.1 nm) + APD: Prx ≈ −11 dBm, margin 17 dB, dispersion 102 ps ≈ acceptable at 10G with small penalty; PIN also works but with less margin. FP/LED fail on dispersion.", hiddenFa: "DFB (Δλ 0.1 nm) + APD: Prx ≈ −11 dBm، حاشیه ۱۷ dB، پاشندگی ۱۰۲ ps در ۱۰G قابل قبول؛ PIN هم کار می‌کند اما با حاشیه کمتر. FP/LED در پاشندگی رد می‌شوند.", constraints: [{ key: "length", op: ">=", value: 60, label: "Length" }, { key: "log10BER", op: "<=", value: -12, label: "BER ≤ 1e-12" }, { key: "errors", op: "<=", value: 0, label: "No physical errors" }], disabled: ["edfa", "raman"], fault: "none" },
  { code: "E", title: "Optimize a WDM system", titleFa: "بهینه‌سازی سیستم WDM", description: "Using Experiment 11, find the channel spacing and per-channel power for 16 × 10 Gb/s over 80 km G.652 that maximizes spectral efficiency while keeping η_FWM < −20 dB and linear crosstalk < −25 dB.", descFa: "با آزمایش ۱۱، فاصله کانال و توان هر کانال را برای ۱۶ × ۱۰ Gb/s روی ۸۰ km G.652 طوری بیابید که بازده طیفی بیشینه و η_FWM < −20 dB و همشنوایی خطی < −25 dB باشد.", timeLimit: 30, hidden: "50 GHz spacing, ≤ 0 dBm/channel on G.652 satisfies both; 25 GHz violates crosstalk at 10G NRZ.", hiddenFa: "فاصله ۵۰ GHz و ≤ 0 dBm در هر کانال روی G.652 هر دو را برآورده می‌کند؛ ۲۵ GHz همشنوایی را در 10G NRZ نقض می‌کند.", constraints: [{ key: "components", op: ">=", value: 1, label: "Report submitted" }], disabled: [], fault: "none" },
  { code: "F", title: "Reduce BER below 1e-12", titleFa: "کاهش BER به زیر 1e-12", description: "A 100 km link with DFB +3 dBm and PIN receiver shows BER ≈ 1e-4. Modify the design (amplifier, APD, DCF, attenuator) to reach BER ≤ 1e-12 without receiver saturation.", descFa: "لینک ۱۰۰ km با DFB +3 dBm و گیرنده PIN دارای BER ≈ 1e-4 است. طراحی را (تقویت‌کننده، APD، DCF، تضعیف‌کننده) تغییر دهید تا BER ≤ 1e-12 بدون اشباع گیرنده حاصل شود.", timeLimit: 30, hidden: "Add EDFA (+20 dB) mid-span or as pre-amp, switch to APD, add 4 km DCF; keep Prx between −25 and −6 dBm.", hiddenFa: "EDFA (+20 dB) در میانه یا به‌عنوان پیش‌تقویت اضافه کنید، به APD بروید، ۴ km DCF بیفزایید؛ Prx را بین −25 و −6 dBm نگه دارید.", constraints: [{ key: "length", op: ">=", value: 100, label: "Length" }, { key: "log10BER", op: "<=", value: -12, label: "BER ≤ 1e-12" }, { key: "errors", op: "<=", value: 0, label: "No physical errors" }], disabled: [], fault: "none" },
  { code: "G", title: "Find the bad splice", titleFa: "تشخیص محل اسپلایس معیوب", description: "In Experiment 8, one of the fusion splices has 0.6 dB loss instead of 0.08 dB. Use 1310 and 1550 nm traces to distinguish it from a bend, and report its position.", descFa: "در آزمایش ۸، یکی از اسپلایس‌های فیوژن به‌جای 0.08 dB تلفات 0.6 dB دارد. با منحنی‌های ۱۳۱۰ و ۱۵۵۰ nm آن را از خمش تمیز دهید و مکانش را گزارش کنید.", timeLimit: 20, hidden: "Splice at 12.0 km: loss is wavelength-independent (unlike a bend which grows with λ).", hiddenFa: "اسپلایس در ۱۲٫۰ km: تلفات مستقل از طول موج است (برخلاف خمش که با λ زیاد می‌شود).", constraints: [{ key: "components", op: ">=", value: 1, label: "Report submitted" }], disabled: [], fault: "splice@12" },
  { code: "H", title: "Design an amplified system", titleFa: "طراحی سیستم با EDFA", description: "Design a 240 km, 10 Gb/s, 1550 nm link with in-line EDFAs. Received power ≥ −20 dBm, OSNR ≥ 20 dB, no receiver overload, dispersion managed.", descFa: "لینک ۲۴۰ km با ۱۰ Gb/s در ۱۵۵۰ nm با EDFAهای میانی طراحی کنید. توان دریافتی ≥ −20 dBm، OSNR ≥ 20 dB، بدون اضافه‌بار گیرنده، پاشندگی مدیریت‌شده.", timeLimit: 45, hidden: "3 × 80 km spans, EDFA +17 dB after each (NF 5), DCF 3 km per span or coherent Rx; launch ≤ +3 dBm per span; OSNR ≈ 58 + 0 − 17 − 5 − 10log3 ≈ 31 dB.", hiddenFa: "۳ span × ۸۰ km، EDFA با +17 dB بعد از هر کدام (NF 5)، ۳ km DCF در هر span یا گیرنده همدوس؛ تزریق ≤ +3 dBm؛ OSNR ≈ 58 + 0 − 17 − 5 − 10log3 ≈ 31 dB.", constraints: [{ key: "length", op: ">=", value: 240, label: "Length" }, { key: "Prx", op: ">=", value: -20, label: "Received power" }, { key: "osnr", op: ">=", value: 20, label: "OSNR" }, { key: "errors", op: "<=", value: 0, label: "No physical errors" }], disabled: [], fault: "none" },
];

const KEYS = ["Prx", "length", "lambda", "margin", "osnr", "log10BER", "totalLoss", "bitRate", "components", "errors"];
const EQUIP = ["led", "fp", "dfb", "tunable", "pulse", "mmf50", "mmf62", "dsf", "nzdsf", "dcf", "edfa", "raman", "splitter", "fbg", "coherent", "apd"];

export function Instructor() {
  const { lang, t, assignments, saveAssignment, deleteAssignment, submissions, setActiveAssignment, setMode, setView } = useStore();
  const [draft, setDraft] = useState<Assignment>({ id: "", title: "", description: "", timeLimit: 30, hidden: "", constraints: [], disabled: [], fault: "none", createdAt: "" });
  const [reveal, setReveal] = useState<Record<string, boolean>>({});
  const [newC, setNewC] = useState<Constraint>({ key: "Prx", op: ">=", value: -18, label: "Received power" });
  const loadScenario = (s: (typeof SCENARIOS)[number]) => setDraft({ id: "", title: lang === "fa" ? s.titleFa : s.title, description: lang === "fa" ? s.descFa : s.description, timeLimit: s.timeLimit, hidden: lang === "fa" ? s.hiddenFa : s.hidden, constraints: s.constraints, disabled: s.disabled, fault: s.fault, createdAt: "" });
  const save = () => { if (!draft.title) return; saveAssignment({ ...draft, id: draft.id || Math.random().toString(36).slice(2, 8), createdAt: new Date().toISOString() }); setDraft({ id: "", title: "", description: "", timeLimit: 30, hidden: "", constraints: [], disabled: [], fault: "none", createdAt: "" }); };
  const open = (id: string) => { setActiveAssignment(id); setMode("free"); setView("free"); };
  return (
    <div className="space-y-4">
      <Callout tone="info" title={<span className="flex items-center gap-1.5"><GraduationCap size={14} />{t("instructor")}</span>}>{lang === "fa" ? "سناریو انتخاب کنید یا تکلیف جدید تعریف کنید: قیود عددی (مقدار واقعی)، پاسخ مخفی، زمان، تجهیزات غیرفعال و خطای تزریق‌شده. دانشجو طراحی خود را در «آزمایش آزاد» ارسال می‌کند و سیستم به‌طور خودکار نمره می‌دهد." : "Pick a real-world scenario or define a new assignment: numeric constraints (true values), hidden reference answer, time limit, disabled equipment and injected faults. Students submit designs from the Free Lab and the system auto-grades them."}</Callout>
      <div className="grid lg:grid-cols-3 gap-4">
        <Panel title={t("realScenarios")} icon={<ClipboardList size={14} />}>
          <div className="space-y-1.5">{SCENARIOS.map((s) => <button key={s.code} onClick={() => loadScenario(s)} className="w-full text-start panel-2 px-3 py-2 hover:border-brand-400 transition"><div className="flex items-center gap-2 text-xs font-semibold"><Badge>{s.code}</Badge>{lang === "fa" ? s.titleFa : s.title}</div><div className="text-[10px] muted mt-1 line-clamp-2">{lang === "fa" ? s.descFa : s.description}</div></button>)}</div>
        </Panel>
        <Panel title={t("createAssignment")} icon={<Plus size={14} />} className="lg:col-span-2">
          <div className="grid md:grid-cols-2 gap-3 text-xs">
            <label className="block"><div className="font-medium mb-1">{t("title")}</div><input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} className="w-full panel-2 px-2.5 py-2 outline-none focus:ring-2 ring-brand-400" /></label>
            <label className="block"><div className="font-medium mb-1">{t("timeLimit")}</div><input type="number" value={draft.timeLimit} onChange={(e) => setDraft({ ...draft, timeLimit: +e.target.value })} className="w-full panel-2 px-2.5 py-2 num outline-none focus:ring-2 ring-brand-400" /></label>
            <label className="block md:col-span-2"><div className="font-medium mb-1">{t("description")}</div><textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} className="w-full h-20 panel-2 px-2.5 py-2 outline-none focus:ring-2 ring-brand-400" /></label>
            <label className="block md:col-span-2"><div className="font-medium mb-1">{t("hiddenAnswer")}</div><textarea value={draft.hidden} onChange={(e) => setDraft({ ...draft, hidden: e.target.value })} className="w-full h-16 panel-2 px-2.5 py-2 outline-none focus:ring-2 ring-brand-400" /></label>
            <div className="md:col-span-2">
              <div className="font-medium mb-1">{t("constraints")}</div>
              <div className="flex flex-wrap gap-1.5 mb-2">{draft.constraints.map((c, i) => <Badge key={i} tone="violet">{c.label}: {c.key} {c.op} {c.value} <button className="ms-1" onClick={() => setDraft({ ...draft, constraints: draft.constraints.filter((_, j) => j !== i) })}>×</button></Badge>)}</div>
              <div className="flex flex-wrap gap-2 items-end">
                <Select label="key" value={newC.key} onChange={(v) => setNewC({ ...newC, key: v })} options={KEYS.map((k) => ({ value: k, label: k }))} />
                <Select label="op" value={newC.op} onChange={(v) => setNewC({ ...newC, op: v as Constraint["op"] })} options={[{ value: ">=", label: ">=" }, { value: "<=", label: "<=" }, { value: "==", label: "==" }]} />
                <label className="block"><div className="font-medium mb-1">{t("value")}</div><input type="number" value={newC.value} onChange={(e) => setNewC({ ...newC, value: +e.target.value })} className="w-24 panel-2 px-2 py-2 num" /></label>
                <label className="block"><div className="font-medium mb-1">label</div><input value={newC.label} onChange={(e) => setNewC({ ...newC, label: e.target.value })} className="w-32 panel-2 px-2 py-2" /></label>
                <Button size="sm" variant="outline" onClick={() => setDraft({ ...draft, constraints: [...draft.constraints, newC] })}><Plus size={12} /></Button>
              </div>
            </div>
            <div><div className="font-medium mb-1">{t("enabledEquipment")}</div><div className="grid grid-cols-2 gap-x-2">{EQUIP.map((e) => <Toggle key={e} checked={!draft.disabled.includes(e)} onChange={(v) => setDraft({ ...draft, disabled: v ? draft.disabled.filter((x) => x !== e) : [...draft.disabled, e] })} label={e} />)}</div></div>
            <div><Select label={t("injectFault")} value={draft.fault} onChange={(v) => setDraft({ ...draft, fault: v })} options={[{ value: "none", label: t("none") }, { value: "bend@22", label: "Bend @ 22 km (OTDR)" }, { value: "splice@12", label: "Bad splice @ 12 km (OTDR)" }, { value: "break@25", label: "Break @ 25 km (OTDR)" }, { value: "dirty-connector", label: "Dirty connector (+1.5 dB)" }, { value: "laser-drift", label: "Laser wavelength drift" }]} /></div>
          </div>
          <div className="mt-3"><Button onClick={save}>{t("save")}</Button></div>
        </Panel>
      </div>
      <div className="grid lg:grid-cols-2 gap-4">
        <Panel title={`${t("assignments")} (${assignments.length})`} icon={<ClipboardList size={14} />}>
          {assignments.length === 0 ? <div className="text-xs muted py-6 text-center">—</div> : assignments.map((a) => (
            <div key={a.id} className="panel-2 p-3 mb-2 text-xs">
              <div className="flex items-center justify-between gap-2"><div className="font-semibold">{a.title}</div><div className="flex gap-1"><Button size="sm" variant="outline" onClick={() => open(a.id)}>{t("openAssignment")}</Button><Button size="sm" variant="ghost" onClick={() => setReveal((r) => ({ ...r, [a.id]: !r[a.id] }))}>{reveal[a.id] ? <EyeOff size={12} /> : <Eye size={12} />}</Button><Button size="sm" variant="danger" onClick={() => deleteAssignment(a.id)}><Trash2 size={12} /></Button></div></div>
              <div className="muted mt-1">{a.description}</div>
              <div className="flex flex-wrap gap-1 mt-1.5">{a.constraints.map((c, i) => <Badge key={i} tone="violet">{c.key} {c.op} {c.value}</Badge>)}{a.fault !== "none" && <Badge tone="bad">{a.fault}</Badge>}{a.disabled.length > 0 && <Badge tone="muted">−{a.disabled.join(", ")}</Badge>}</div>
              {reveal[a.id] && <Callout tone="warn" title={t("hiddenAnswer")}>{a.hidden || "—"}</Callout>}
            </div>
          ))}
        </Panel>
        <Panel title={`${t("submissions")} (${submissions.length})`} icon={<Users size={14} />}>
          {submissions.length === 0 ? <div className="text-xs muted py-6 text-center">—</div> : [...submissions].reverse().map((s) => { const a = assignments.find((x) => x.id === s.assignmentId); return (
            <div key={s.id} className="panel-2 p-3 mb-2 text-xs">
              <div className="flex items-center justify-between"><div className="font-semibold">{a?.title ?? s.assignmentId}</div><div className="flex items-center gap-2"><span className="muted num text-[10px]">{new Date(s.time).toLocaleString()}</span><Badge tone={s.score >= 70 ? "good" : s.score >= 40 ? "warn" : "bad"}>{t("score")} {s.score}/100</Badge></div></div>
              <ul className="mt-1.5 space-y-0.5">{s.details.map((d, i) => <li key={i} className={d.pass ? "text-emerald-500" : "text-rose-500"}>{d.pass ? "✓" : "✗"} {d.label}</li>)}</ul>
              <div className="num text-[10px] muted mt-1">Prx {s.metrics.Prx?.toFixed(1)} dBm · L {s.metrics.length?.toFixed(1)} km · OSNR {s.metrics.osnr?.toFixed(1)} dB · log BER {s.metrics.log10BER?.toFixed(1)}</div>
            </div>
          ); })}
        </Panel>
      </div>
    </div>
  );
}
export { SCENARIOS };
