import { useMemo, useState } from "react";
import { FlaskConical, Play, Save, Download, Trash2 } from "lucide-react";
import { useStore, download } from "../lib/store";
import { Panel, Button, Select, Slider, Stat, Badge, Callout, fmt, Segmented } from "../components/ui";
import { XYChart, ScatterFit, Palette } from "../components/Chart";
import * as P from "../lib/physics";

type Fn = { id: string; en: string; fa: string; x: { en: string; fa: string; unit: string; min: number; max: number }; y: { en: string; fa: string; unit: string }; params: { key: string; label: string; min: number; max: number; step: number; def: number }[]; f: (x: number, p: Record<string, number>) => number; log?: boolean };
const FNS: Fn[] = [
  { id: "att", en: "Attenuation vs wavelength", fa: "تضعیف بر حسب طول موج", x: { en: "λ", fa: "λ", unit: "nm", min: 800, max: 1700 }, y: { en: "α", fa: "α", unit: "dB/km" }, params: [{ key: "oh", label: "OH⁻ peak (dB/km)", min: 0, max: 2, step: 0.05, def: 0.5 }], f: (x, p) => P.attenuationSpectrum(x, p.oh) },
  { id: "disp", en: "Dispersion vs wavelength", fa: "پاشندگی بر حسب طول موج", x: { en: "λ", fa: "λ", unit: "nm", min: 1250, max: 1650 }, y: { en: "D", fa: "D", unit: "ps/(nm·km)" }, params: [{ key: "l0", label: "λ₀ (nm)", min: 1280, max: 1560, step: 1, def: 1310 }, { key: "s0", label: "S₀ (ps/nm²/km)", min: 0.04, max: 0.1, step: 0.001, def: 0.092 }], f: (x, p) => P.dispersionSMF(x, p.l0, p.s0) },
  { id: "v", en: "V-number vs wavelength", fa: "عدد V بر حسب طول موج", x: { en: "λ", fa: "λ", unit: "nm", min: 600, max: 1700 }, y: { en: "V", fa: "V", unit: "" }, params: [{ key: "a", label: "a (µm)", min: 1, max: 31, step: 0.1, def: 4.1 }, { key: "na", label: "NA", min: 0.05, max: 0.3, step: 0.005, def: 0.12 }], f: (x, p) => P.vNumber(p.a, x, p.na) },
  { id: "mfd", en: "Mode-field diameter vs wavelength", fa: "قطر میدان مود بر حسب طول موج", x: { en: "λ", fa: "λ", unit: "nm", min: 1200, max: 1700 }, y: { en: "MFD", fa: "MFD", unit: "µm" }, params: [{ key: "a", label: "a (µm)", min: 3, max: 6, step: 0.05, def: 4.1 }, { key: "na", label: "NA", min: 0.08, max: 0.2, step: 0.005, def: 0.12 }], f: (x, p) => P.mfd(p.a, P.vNumber(p.a, x, p.na)) },
  { id: "bend", en: "Bend loss vs radius", fa: "تلفات خمش بر حسب شعاع", x: { en: "R", fa: "R", unit: "mm", min: 4, max: 40 }, y: { en: "Loss / turn", fa: "تلفات هر دور", unit: "dB" }, params: [{ key: "lam", label: "λ (nm)", min: 1260, max: 1650, step: 5, def: 1550 }, { key: "dn", label: "n₁−n₂", min: 0.003, max: 0.012, step: 0.0001, def: 0.005 }], f: (x, p) => Math.min(60, P.bendLossPerTurn(x, 4.1, p.lam, 1.4504, 1.4504 - p.dn)), log: true },
  { id: "ber", en: "BER vs received power", fa: "BER بر حسب توان دریافتی", x: { en: "P_r", fa: "P_r", unit: "dBm", min: -40, max: -5 }, y: { en: "BER", fa: "BER", unit: "" }, params: [{ key: "br", label: "Bit rate (Gb/s)", min: 1, max: 100, step: 1, def: 10 }, { key: "M", label: "APD gain M (1 = PIN)", min: 1, max: 40, step: 1, def: 1 }], f: (x, p) => Math.max(1e-16, P.receiverPerformance({ type: p.M > 1 ? "apd" : "pin", PrDbm: x, R: 0.9, M: p.M, x: 0.7, bwGHz: 0.75 * p.br, Id: 5, T: 300, RL: 50, extinction: 10, format: "nrz" }).ber), log: true },
  { id: "edfaPump", en: "EDFA gain vs pump power", fa: "بهره EDFA بر حسب توان پمپ", x: { en: "P_pump", fa: "P_pump", unit: "mW", min: 5, max: 400 }, y: { en: "Gain", fa: "بهره", unit: "dB" }, params: [{ key: "pin", label: "P_in (dBm)", min: -40, max: 5, step: 0.5, def: -20 }, { key: "len", label: "Er length (m)", min: 1, max: 40, step: 0.5, def: 10 }], f: (x, p) => P.edfa({ PinDbm: p.pin, pumpMw: x, lengthM: p.len, nsp: 1.5, lambda: 1550, model: "ideal" }).gainDb },
  { id: "edfaPin", en: "EDFA gain vs input power", fa: "بهره EDFA بر حسب توان ورودی", x: { en: "P_in", fa: "P_in", unit: "dBm", min: -40, max: 5 }, y: { en: "Gain", fa: "بهره", unit: "dB" }, params: [{ key: "pump", label: "Pump (mW)", min: 5, max: 400, step: 5, def: 100 }], f: (x, p) => P.edfa({ PinDbm: x, pumpMw: p.pump, lengthM: 10, nsp: 1.5, lambda: 1550, model: "ideal" }).gainDb },
  { id: "link", en: "Received power vs link length", fa: "توان دریافتی بر حسب طول لینک", x: { en: "L", fa: "L", unit: "km", min: 1, max: 200 }, y: { en: "P_rx", fa: "P_rx", unit: "dBm" }, params: [{ key: "pt", label: "P_tx (dBm)", min: -10, max: 20, step: 0.5, def: 0 }, { key: "alpha", label: "α (dB/km)", min: 0.15, max: 0.5, step: 0.01, def: 0.2 }, { key: "split", label: "Splitter N", min: 1, max: 64, step: 1, def: 1 }], f: (x, p) => P.linkBudget({ Pt: p.pt, L: x, alpha: p.alpha, nConn: 2, connLoss: 0.5, nSplice: Math.round(x / 5), spliceLoss: 0.1, splitN: p.split, splitExcess: 1, couplerLoss: 0, gain: 0, sens: -28, margin: 3 }).Pr },
  { id: "chrom", en: "Pulse broadening vs length", fa: "پهن‌شدگی پالس بر حسب طول", x: { en: "L", fa: "L", unit: "km", min: 1, max: 200 }, y: { en: "T_out", fa: "T_out", unit: "ps" }, params: [{ key: "D", label: "D (ps/nm/km)", min: -20, max: 25, step: 0.5, def: 17 }, { key: "dl", label: "Δλ (nm)", min: 0.01, max: 5, step: 0.01, def: 0.1 }, { key: "t0", label: "T₀ (ps)", min: 5, max: 500, step: 5, def: 100 }], f: (x, p) => Math.sqrt(p.t0 ** 2 + P.chromaticBroadening(p.D, x, p.dl) ** 2) },
  { id: "fbgT", en: "FBG Bragg shift vs temperature", fa: "جابه‌جایی براگ بر حسب دما", x: { en: "ΔT", fa: "ΔT", unit: "°C", min: -40, max: 150 }, y: { en: "Δλ_B", fa: "Δλ_B", unit: "pm" }, params: [{ key: "strain", label: "Strain (µε)", min: 0, max: 3000, step: 10, def: 0 }], f: (x, p) => P.fbg({ periodNm: 535.2, neff: 1.4482, lengthMm: 10, dn: 1e-4, dT: x, strainUe: p.strain, N: 4 }).shift * 1000 },
  { id: "pmd", en: "PMD vs link length", fa: "PMD بر حسب طول لینک", x: { en: "L", fa: "L", unit: "km", min: 1, max: 2000 }, y: { en: "Δτ", fa: "Δτ", unit: "ps" }, params: [{ key: "d", label: "D_PMD (ps/√km)", min: 0.02, max: 2, step: 0.01, def: 0.1 }], f: (x, p) => P.pmdDelay(p.d, x) },
  { id: "spm", en: "SPM phase vs launch power", fa: "فاز SPM بر حسب توان تزریق", x: { en: "P₀", fa: "P₀", unit: "mW", min: 1, max: 500 }, y: { en: "φ_SPM", fa: "φ_SPM", unit: "rad" }, params: [{ key: "g", label: "γ (W⁻¹km⁻¹)", min: 0.5, max: 20, step: 0.1, def: 1.3 }, { key: "L", label: "L (km)", min: 1, max: 200, step: 1, def: 50 }], f: (x, p) => P.nonlinearMetrics({ P0mW: x, gamma: p.g, Lkm: p.L, alphaDb: 0.2, Aeff: 80, linewidthMHz: 10, nCh: 1, spacingGHz: 50, D: 17, lambda: 1550 }).phiSPM },
  { id: "fwm", en: "FWM efficiency vs channel spacing", fa: "بازده FWM بر حسب فاصله کانال", x: { en: "Δf", fa: "Δf", unit: "GHz", min: 5, max: 200 }, y: { en: "η_FWM", fa: "η_FWM", unit: "dB" }, params: [{ key: "D", label: "D (ps/nm/km)", min: -2, max: 20, step: 0.1, def: 17 }, { key: "L", label: "L (km)", min: 1, max: 200, step: 1, def: 80 }], f: (x, p) => 10 * Math.log10(Math.max(1e-9, P.nonlinearMetrics({ P0mW: 1, gamma: 1.3, Lkm: p.L, alphaDb: 0.2, Aeff: 80, linewidthMHz: 10, nCh: 2, spacingGHz: x, D: p.D, lambda: 1550 }).etaFWM)) },
  { id: "modal", en: "Modal bandwidth vs Δ", fa: "پهنای باند مودی بر حسب Δ", x: { en: "Δ", fa: "Δ", unit: "%", min: 0.2, max: 3 }, y: { en: "B·L", fa: "B·L", unit: "MHz·km" }, params: [{ key: "g", label: "Graded (1) / step (0)", min: 0, max: 1, step: 1, def: 1 }], f: (x, p) => { const n1 = 1.48, n2 = n1 * (1 - x / 100); return 440 / P.modalDispersion(n1, n2, 1, p.g ? "graded" : "step"); }, log: true },
];

interface Scenario { id: string; name: string; fnId: string; params: Record<string, number>; data: { x: number; y: number }[] }

export function Research() {
  const { lang, t } = useStore();
  const [fnId, setFnId] = useState("att");
  const fn = FNS.find((f) => f.id === fnId)!;
  const [range, setRange] = useState<{ a: number; b: number; n: number }>({ a: fn.x.min, b: fn.x.max, n: 60 });
  const [params, setParams] = useState<Record<string, number>>(Object.fromEntries(fn.params.map((p) => [p.key, p.def])));
  const [fitType, setFitType] = useState<"linear" | "exp" | "power" | "poly2">("linear");
  const [scenarios, setScenarios] = useState<Scenario[]>([]);
  const [ran, setRan] = useState(0);
  const changeFn = (id: string) => { const f = FNS.find((x) => x.id === id)!; setFnId(id); setRange({ a: f.x.min, b: f.x.max, n: 60 }); setParams(Object.fromEntries(f.params.map((p) => [p.key, p.def]))); setRan(0); };
  const data = useMemo(() => { void ran; return P.linspace(range.a, range.b, range.n).map((x) => ({ x: +x.toFixed(4), y: +fn.f(x, params).toPrecision(6) })).filter((d) => Number.isFinite(d.y)); }, [fn, range, params, ran]);
  const fit = useMemo(() => { const xs = data.map((d) => d.x), ys = data.map((d) => d.y); if (xs.length < 3) return null; if (fitType === "linear") return P.fitLinear(xs, ys); if (fitType === "exp") return P.fitExp(xs, ys); if (fitType === "power") return P.fitPower(xs, ys); return P.fitPoly2(xs, ys); }, [data, fitType]);
  const stats = useMemo(() => { if (data.length < 3) return null; const ys = data.map((d) => d.y); const iMin = ys.indexOf(Math.min(...ys)), iMax = ys.indexOf(Math.max(...ys)); const mid = Math.floor(data.length / 2); const dy = (data[mid + 1].y - data[mid - 1].y) / (data[mid + 1].x - data[mid - 1].x); const elasticity = (dy * data[mid].x) / (data[mid].y || 1e-12); return { min: data[iMin], max: data[iMax], slope: dy, elasticity }; }, [data]);
  const sensTable = useMemo(() => fn.params.map((p) => { const mid = (range.a + range.b) / 2; const base = fn.f(mid, params); const d = p.step * 5; const up = fn.f(mid, { ...params, [p.key]: params[p.key] + d }); const s = ((up - base) / (base || 1e-12)) / (d / (params[p.key] || 1e-12)); return { key: p.key, label: p.label, s }; }), [fn, params, range]);
  const overlay = useMemo(() => { const all = [{ id: "current", name: lang === "fa" ? "فعلی" : "current", data }, ...scenarios.filter((s) => s.fnId === fnId)]; const xs = Array.from(new Set(all.flatMap((s) => s.data.map((d) => d.x)))).sort((a, b) => a - b); return { series: all, rows: xs.map((x) => { const row: Record<string, number | undefined> = { x }; all.forEach((s) => { const pt = s.data.find((d) => Math.abs(d.x - x) < 1e-9); row[s.id] = pt?.y; }); return row; }) }; }, [data, scenarios, fnId, lang]);
  return (
    <div className="space-y-4">
      <Callout tone="info" title={<span className="flex items-center gap-1.5"><FlaskConical size={14} />{t("research")}</span>}>{lang === "fa" ? "یک تابع فیزیکی انتخاب کنید، بازه جاروب و پارامترهای ثابت را تنظیم کنید، سپس اجرا کنید. سیستم برازش منحنی، حساسیت (کشسانی ∂lny/∂lnx)، بهینه و مقایسه سناریوها را انجام می‌دهد." : "Choose a physical function, set the sweep range and fixed parameters, then run. The system performs curve fitting, sensitivity (elasticity ∂ln y/∂ln x), optimization and multi-scenario comparison."}</Callout>
      <div className="grid lg:grid-cols-4 gap-4">
        <Panel title={t("sweep")} className="space-y-3">
          <Select label={lang === "fa" ? "تابع" : "Function"} value={fnId} onChange={changeFn} options={FNS.map((f) => ({ value: f.id, label: lang === "fa" ? f.fa : f.en }))} />
          <div className="grid grid-cols-2 gap-2 text-xs"><label><div className="mb-1">{t("from")} ({fn.x.unit})</div><input type="number" value={range.a} onChange={(e) => setRange({ ...range, a: +e.target.value })} className="w-full panel-2 px-2 py-1.5 num" /></label><label><div className="mb-1">{t("to")} ({fn.x.unit})</div><input type="number" value={range.b} onChange={(e) => setRange({ ...range, b: +e.target.value })} className="w-full panel-2 px-2 py-1.5 num" /></label></div>
          <Slider label={t("points")} value={range.n} min={10} max={300} step={10} onChange={(v) => setRange({ ...range, n: v })} />
          {fn.params.map((p) => <Slider key={p.key} label={p.label} value={params[p.key]} min={p.min} max={p.max} step={p.step} onChange={(v) => setParams({ ...params, [p.key]: v })} fmt={(v) => (p.step < 0.01 ? v.toFixed(4) : v % 1 === 0 ? String(v) : v.toFixed(2))} />)}
          <div className="flex flex-wrap gap-2"><Button onClick={() => setRan((r) => r + 1)}><Play size={12} />{t("run")}</Button><Button variant="outline" onClick={() => setScenarios((s) => [...s, { id: Math.random().toString(36).slice(2, 7), name: `${lang === "fa" ? "سناریو" : "Scenario"} ${s.length + 1} (${fn.params.map((p) => `${p.key}=${params[p.key]}`).join(", ")})`, fnId, params: { ...params }, data }])}><Save size={12} />{t("addScenario")}</Button><Button variant="outline" onClick={() => download(`sweep-${fnId}.csv`, ["x,y", ...data.map((d) => `${d.x},${d.y}`)].join("\n"), "text/csv")}><Download size={12} />CSV</Button></div>
        </Panel>
        <Panel title={`${lang === "fa" ? fn.y.fa : fn.y.en} vs ${lang === "fa" ? fn.x.fa : fn.x.en}`} className="lg:col-span-3">
          <XYChart data={overlay.rows} series={overlay.series.map((s, i) => ({ key: s.id, name: s.name, color: Palette[i % Palette.length] }))} xLabel={`${fn.x.en} (${fn.x.unit})`} yLabel={`${fn.y.en} ${fn.y.unit ? "(" + fn.y.unit + ")" : ""}`} height={300} logY={fn.log} legend refX={stats ? [{ x: stats.min.x, label: "min", color: "#10b981" }, { x: stats.max.x, label: "max", color: "#f43f5e" }] : []} />
        </Panel>
      </div>
      <div className="grid lg:grid-cols-3 gap-4">
        <Panel title={t("fit")} right={<Segmented size="xs" value={fitType} onChange={setFitType} options={[{ value: "linear", label: "linear" }, { value: "exp", label: "exp" }, { value: "power", label: "power" }, { value: "poly2", label: "poly²" }]} />}>
          {fit ? <><ScatterFit points={data} fit={fit.f} xLabel={fn.x.en} yLabel={fn.y.en} height={220} /><div className="mt-2 text-xs"><div className="eq">{fit.label}</div><div className="mt-1 flex items-center gap-2"><Badge tone={fit.r2 > 0.98 ? "good" : fit.r2 > 0.9 ? "warn" : "bad"}>R² = {fit.r2.toFixed(4)}</Badge></div></div></> : <div className="text-xs muted py-6 text-center">{lang === "fa" ? "این برازش برای داده‌های منفی/صفر تعریف نشده است." : "This fit is undefined for non-positive data."}</div>}
        </Panel>
        <Panel title={`${t("optimum")} & ${t("sensitivity")}`}>
          {stats && <div className="grid grid-cols-2 gap-2 mb-3"><Stat label="min" value={stats.min.y.toPrecision(4)} unit={fn.y.unit} sub={`@ ${fn.x.en} = ${stats.min.x}`} tone="good" /><Stat label="max" value={stats.max.y.toPrecision(4)} unit={fn.y.unit} sub={`@ ${fn.x.en} = ${stats.max.x}`} tone="bad" /><Stat label="dy/dx (mid)" value={stats.slope.toPrecision(3)} unit={`${fn.y.unit}/${fn.x.unit}`} /><Stat label="∂ln y/∂ln x" value={fmt(stats.elasticity, 3)} tone="brand" /></div>}
          <div className="text-xs font-semibold mb-1">{lang === "fa" ? "حساسیت به پارامترهای ثابت (کشسانی)" : "Sensitivity to fixed parameters (elasticity)"}</div>
          <table className="w-full text-xs"><tbody>{sensTable.map((s) => <tr key={s.key} className="border-t border-line"><td className="py-1">{s.label}</td><td className="num text-end">{Number.isFinite(s.s) ? s.s.toFixed(3) : "—"}</td><td className="w-1/2 ps-2"><div className="h-1.5 rounded-full bg-black/5 dark:bg-white/10 overflow-hidden"><div className={`h-full ${s.s >= 0 ? "bg-brand-500" : "bg-rose-500"}`} style={{ width: `${Math.min(100, Math.abs(s.s) * 30)}%` }} /></div></td></tr>)}</tbody></table>
        </Panel>
        <Panel title={`${t("scenarios")} (${scenarios.length})`}>
          {scenarios.length === 0 ? <div className="text-xs muted py-6 text-center">{lang === "fa" ? "سناریویی ذخیره نشده است." : "No saved scenarios."}</div> : scenarios.map((s, i) => <div key={s.id} className="flex items-center justify-between text-xs panel-2 px-2.5 py-1.5 mb-1.5"><span className="flex items-center gap-2 truncate"><span className="w-2.5 h-2.5 rounded-full shrink-0" style={{ background: Palette[(i + 1) % Palette.length] }} /><span className="truncate">{s.name}</span>{s.fnId !== fnId && <Badge tone="muted">{FNS.find((f) => f.id === s.fnId)?.en}</Badge>}</span><button onClick={() => setScenarios((sc) => sc.filter((x) => x.id !== s.id))}><Trash2 size={12} className="muted" /></button></div>)}
        </Panel>
      </div>
    </div>
  );
}
